#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF0DC8E00B28C5995 (bod@debian.org)
#
Name     : help2man
Version  : 1.47.11
Release  : 16
URL      : https://mirrors.kernel.org/gnu/help2man/help2man-1.47.11.tar.xz
Source0  : https://mirrors.kernel.org/gnu/help2man/help2man-1.47.11.tar.xz
Source1 : https://mirrors.kernel.org/gnu/help2man/help2man-1.47.11.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: help2man-bin = %{version}-%{release}
Requires: help2man-license = %{version}-%{release}
Requires: help2man-man = %{version}-%{release}

%description
help2man is a script to create simple man pages from the --help and
--version output of programs.

%package bin
Summary: bin components for the help2man package.
Group: Binaries
Requires: help2man-license = %{version}-%{release}

%description bin
bin components for the help2man package.


%package doc
Summary: doc components for the help2man package.
Group: Documentation
Requires: help2man-man = %{version}-%{release}

%description doc
doc components for the help2man package.


%package license
Summary: license components for the help2man package.
Group: Default

%description license
license components for the help2man package.


%package man
Summary: man components for the help2man package.
Group: Default

%description man
man components for the help2man package.


%prep
%setup -q -n help2man-1.47.11
cd %{_builddir}/help2man-1.47.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573417312
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1573417312
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/help2man
cp %{_builddir}/help2man-1.47.11/COPYING %{buildroot}/usr/share/package-licenses/help2man/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/help2man-1.47.11/debian/copyright %{buildroot}/usr/share/package-licenses/help2man/119eacdff9a5df0da51a43de46e250c3bb1c00fe
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/help2man

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/help2man/119eacdff9a5df0da51a43de46e250c3bb1c00fe
/usr/share/package-licenses/help2man/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/help2man.1
